const SET_THREAD = 'SET_THREAD'
const SET_POST = 'SET_POST'
const SET_USER = 'SET_USER'
const SET_AUTH_USER = 'SET_AUTH_USER'
const SET_ITEM = 'SET_ITEM'

const ADD_CONTRIBUTOR_TO_THREAD = 'ADD_CONTRIBUTOR_TO_THREAD'
const ADD_POST_TO_THREAD = 'ADD_POST_TO_THREAD'
const ADD_POST_TO_USER = 'ADD_POST_TO_USER'
const ADD_THREAD_TO_FORUM = 'ADD_THREAD_TO_FORUM'
const ADD_THREAD_T0_USER = 'ADD_THREAD_T0_USER'

export { SET_THREAD, SET_POST, SET_USER, SET_AUTH_USER, SET_ITEM, ADD_POST_TO_THREAD, ADD_CONTRIBUTOR_TO_THREAD, ADD_POST_TO_USER, ADD_THREAD_TO_FORUM, ADD_THREAD_T0_USER }
